name: Creative Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches: 
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Creative Message
      run: echo "This is a creative workflow! 🎉"

    - name: Generate Artwork
      run: echo "Creating artwork..."
    - name: Upload Artwork Image
      uses: actions/upload-artifact@v2
      with:
        name: Artwork Image
        path: /path/to/artwork/image.png
        
    
